ssid: !secret wifi_ssid
password: !secret wifi_password
manual_ip:
  static_ip: ${static_ip}
  gateway: 192.168.2.1
  subnet: 255.255.255.0
ap:
  ssid: ${ap_ssid}
  password: !secret ap_fallback_key
on_connect:
  - script.execute: draw_display
on_disconnect:
  - script.execute: draw_display
