esphome:
  name: "Kamera 01"
  friendly_name: "Kamera 01"




esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG 

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_enc_key

ota:
 - platform: esphome
   password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: 192.168.2.61
    gateway: 192.168.2.1
    subnet: 255.255.255.0

  ap:
    ssid: "Cam01 Fallback Hotspot"
    password: !secret ap_fallback_key

captive_portal:

esp32_camera:
  name: esp32_cam
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 800x600

esp32_camera_web_server:
  - port: 80
    mode: stream
  - port: 81
    mode: snapshot

output:
  - platform: ledc
    channel: 2
    id: flash_led
    pin: GPIO4

binary_sensor:
  - platform: status
    name: "ESP32Cam status"

sensor:
  - platform: wifi_signal
    name: "ESP32Cam WiFi Signal"
    update_interval: 60s
    
light:
  - platform: binary
    output: flash_led
    name: "ESP32Cam light"