substitutions:
  name: screen-01
  friendly_name: Screen 01
  static_ip: 192.168.2.45

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: DEBUG

api: !include ./includes/api.yaml
ota: 
- platform: esphome
  password: !secret ota_password

wifi: !include ./includes/wifi_common.yaml
captive_portal:
# web_server: !include ./includes/web.yaml

i2c:
  sda: GPIO22
  scl: GPIO23
  scan: true

font:
  - file: "fonts/UbuntuMono-Regular.ttf"
    id: font_10
    size: 12

display:
  - platform: ssd1306_i2c
    model: SSD1305_128X64
    id: oled_display
    lambda: |-
      it.print(0, 0, id(font_10), "Hello");

interval:
  - interval: 2s
    then:
      - lambda: 'id(oled_display).update();'
